### PR TITLE
put collaction api fetch post into module and minor bug fixing

### PR DESCRIPTION
**Pull request by key60529**
put collaction api fetch post into module then include into all news-{locale}.jade
and
fixing the news-en.jade appending the old element structure

### CODE REVIEW

**Comment by UnKnoWn-Consortium** [comment]
Would it be even better if we create a dedicated JavaScript file, say `index.js`, and put all JavaScript into it? Frankly, I am not quite comfortable about putting scripts into templates.

**Comment by key60529** [comment]
You have your point, then I would suggest to do the following https://github.com/g0vhk-io/hongkong-extradition/pull/57#issuecomment-503565302 at the same time so it will easier to manage the structure and the script, but seems it become much more bigger, so I need green light from @nandiheath to move forward

**Comment by UnKnoWn-Consortium** [comment]
@key60529 Agreed. I will try to see if I can submit a pull request tonight.

**Comment by nandiheath** [comment]
Maybe we could discuss here since the issues page not enabled yet lol

I agree with @UnKnoWn-Consortium that the template should keep javascript out, and creating a separate module file is much better. So I would wait for another PR and just keep this one for a while for discussion purpose.

As @key60529 mentioned in #57 , i am not sure how could you extract the layout of the indice, since most of the content from index pages are already language specific. Or you should show me by just submitting a dummy PR? not necessary for it to work, just show the concept how you gonna organize the structure.

**Comment by key60529** [comment]
> Maybe we could discuss here since the issues page not enabled yet lol
> 
> I agree with @UnKnoWn-Consortium that the template should keep javascript out, and creating a separate module file is much better. So I would wait for another PR and just keep this one for a while for discussion purpose.
> 
> As @key60529 mentioned in #57 , i am not sure how could you extract the layout of the indice, since most of the content from index pages are already language specific. Or you should show me by just submitting a dummy PR? not necessary for it to work, just show the concept how you gonna organize the structure.

What do you think if we compile the jade to php ? Then we could create a simple i18n function for managing all the language string. At the same time we could consolidate all the {module}-{locale}.jade into one file as {module}.jade and use the i18n function to echo the string from /i18n/{locale}.php

**Comment by nandiheath** [comment]
> > Maybe we could discuss here since the issues page not enabled yet lol
> > I agree with @UnKnoWn-Consortium that the template should keep javascript out, and creating a separate module file is much better. So I would wait for another PR and just keep this one for a while for discussion purpose.
> > As @key60529 mentioned in #57 , i am not sure how could you extract the layout of the indice, since most of the content from index pages are already language specific. Or you should show me by just submitting a dummy PR? not necessary for it to work, just show the concept how you gonna organize the structure.
> 
> What do you think if we compile the jade to php ? Then we could create a simple i18n function for managing all the language string. At the same time we could consolidate all the {module}-{locale}.jade into one file as {module}.jade and use the i18n function to echo the string from /i18n/{locale}.php

IMO introducing `php` to this project will add extra complexity. i think in this case javascript is an even better solution as there is already dependencies. But first of all we should seek for the native i18n support of this template engine (if any)

**Comment by key60529** [comment]
> > > Maybe we could discuss here since the issues page not enabled yet lol
> > > I agree with @UnKnoWn-Consortium that the template should keep javascript out, and creating a separate module file is much better. So I would wait for another PR and just keep this one for a while for discussion purpose.
> > > As @key60529 mentioned in #57 , i am not sure how could you extract the layout of the indice, since most of the content from index pages are already language specific. Or you should show me by just submitting a dummy PR? not necessary for it to work, just show the concept how you gonna organize the structure.
> > 
> > 
> > What do you think if we compile the jade to php ? Then we could create a simple i18n function for managing all the language string. At the same time we could consolidate all the {module}-{locale}.jade into one file as {module}.jade and use the i18n function to echo the string from /i18n/{locale}.php
> 
> IMO introducing `php` to this project will add extra complexity. i think in this case javascript is an even better solution as there is already dependencies. But first of all we should seek for the native i18n support of this template engine (if any)

After googled, I guess there's no native support for jade template, then maybe [this one] (https://www.i18next.com/overview/getting-started) would be the best option.

**Comment by UnKnoWn-Consortium** [comment]
I think it is about whether we intend to keep this site a single-page site or refactor it into a single-page app. The current site is fully accessible even if a user has turned JavaScript off. I am not sure if it is intentional or just implicitly inherited from the g0v.tw template. 

If the former is true, Jade/Pug template engine does support interpolation of variables from an external key-value storage (say a JSON). If our fellow collaborators can accept amending multilingual contents out of templates, this is the best way to resolve the code duplication and maintenance issue.

**Comment by UnKnoWn-Consortium** [comment]
JS refactoring now available in #60. 

P.S. I am also working on a new Webpack build script that can replace the `server.ls` with something we are more familiar with.

**Comment by key60529** [comment]
> JS refactoring now available in #60. I have also created a new class for loading and serving articles from Collaction.
> 
> P.S. I am also working on a new Webpack build script that can replace the `server.ls` with something we are more familiar with.

Thanks for what you done, sorry it’s been too busy for me and just have some spare time could keep track on this biggest project, let me
know if you need any help with the webpack build!

**Pull request closed without merging**
