### PR TITLE
little UI enhancement

### PR DESCRIPTION
**Pull request by key60529**
mainly focus on the news section, try to make it more easy to read and go through, and some little enhancement on the buttons etc......

### CODE REVIEW

**Comment by key60529** [comment]
Sorry, I guess I miss a class for those button, let me check and commit again

**Comment by key60529** [comment]
Hi @nandiheath , just commit a new changes to fix the issue, please feel free to pull and compiled again to see wether the issue are fixed or not 😊

**Comment by nandiheath** [comment]
For mobile version there is a minor issues on the buttons
It would be great if you can submit another PR for fixing this issue
I will merge this PR first. Thank you

Screenshot 2019-06-13 at 11 04 11 PM

**Comment by key60529** [comment]
Noted, just notice that the layout on mobile doesn't seems to show as expected, will go through and create another PR for fixing.

**Pull request merged**
