### PR TITLE
Retrofitting design of the background section

### PR DESCRIPTION
**Pull request by UnKnoWn-Consortium**
(1) Updated element structure of background; and
(2) Wrapped contents with wells

### CODE REVIEW

**Comment by nandiheath** [comment]
any reason changing the background colour and also the way of presentation? it looks a little bit weird comparing to other layout.

and would love to have screenshots that comparing the before and after of the PR. thank you very much for the contributions.

**Comment by UnKnoWn-Consortium** [comment]
I am thinking of reordering the sections and it is the first step. The current presentation and flow is a little bit awkward. It would look more reasonable if "Background" section is at the top with "Why" section following immediately. To distinguish both sections, I have adopted the "well" style from Bootstrap 3. 

Screenshot 1
Screenshot 2

**Comment by nandiheath** [comment]
agree with your points. but since this may be a quite big change I need one more upvote then i will merge this PR.

**Comment by key60529** [comment]
I agree with @UnKnoWn-Consortium, I have the same though since I joined the contribution.
This will make much more sense for some user which wanna know the reason of the whole point.

**Comment by UnKnoWn-Consortium** [comment]
@nandiheath Thanks for merging. I will proceed with the reordering pull request.

**Pull request merged**
